version: '3'

services:
  backend:
    container_name: videoicfes_back
    restart: always
    build: ./server
    links:
      - mongodb
    ports:
      - 3300:3300
    networks:
      - network-backend
    env_file: ./server/.env

  mongodb:
    container_name: videoicfes_database
    restart: always
    image: mongo:4.4.19-focal
    # image: mongo:latest
    expose:
      - 27017
    volumes:
      - mongodb_data:/data/db
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: root
      ME_CONFIG_BASICAUTH_PASSWORD: root
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
    networks:
      - network-backend

networks:
  network-backend:
    driver: bridge
volumes:
  mongodb_data:
    external: true